window.esdocSearchIndex = [
  [
    "projext/src/services/configurations/babelconfiguration.js~babelconfiguration",
    "class/src/services/configurations/babelConfiguration.js~BabelConfiguration.html",
    "<span>BabelConfiguration</span> <span class=\"search-result-import-path\">projext/src/services/configurations/babelConfiguration.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/buildcleaner.js~buildcleaner",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html",
    "<span>BuildCleaner</span> <span class=\"search-result-import-path\">projext/src/services/building/buildCleaner.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/buildcopier.js~buildcopier",
    "class/src/services/building/buildCopier.js~BuildCopier.html",
    "<span>BuildCopier</span> <span class=\"search-result-import-path\">projext/src/services/building/buildCopier.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/buildengines.js~buildengines",
    "class/src/services/building/buildEngines.js~BuildEngines.html",
    "<span>BuildEngines</span> <span class=\"search-result-import-path\">projext/src/services/building/buildEngines.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/buildnoderunner.js~buildnoderunner",
    "class/src/services/building/buildNodeRunner.js~BuildNodeRunner.html",
    "<span>BuildNodeRunner</span> <span class=\"search-result-import-path\">projext/src/services/building/buildNodeRunner.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html",
    "<span>BuildNodeRunnerProcess</span> <span class=\"search-result-import-path\">projext/src/services/building/buildNodeRunnerProcess.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/buildtranspiler.js~buildtranspiler",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html",
    "<span>BuildTranspiler</span> <span class=\"search-result-import-path\">projext/src/services/building/buildTranspiler.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/buildversion.js~buildversion",
    "class/src/services/building/buildVersion.js~BuildVersion.html",
    "<span>BuildVersion</span> <span class=\"search-result-import-path\">projext/src/services/building/buildVersion.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/builder.js~builder",
    "class/src/services/building/builder.js~Builder.html",
    "<span>Builder</span> <span class=\"search-result-import-path\">projext/src/services/building/builder.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/cli.js~cli",
    "class/src/services/cli/cli.js~CLI.html",
    "<span>CLI</span> <span class=\"search-result-import-path\">projext/src/services/cli/cli.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clibuild.js~clibuildcommand",
    "class/src/services/cli/cliBuild.js~CLIBuildCommand.html",
    "<span>CLIBuildCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliBuild.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/cliclean.js~clicleancommand",
    "class/src/services/cli/cliClean.js~CLICleanCommand.html",
    "<span>CLICleanCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliClean.js</span>",
    "class"
  ],
  [
    "projext/src/abstracts/clicommand.js~clicommand",
    "class/src/abstracts/cliCommand.js~CLICommand.html",
    "<span>CLICommand</span> <span class=\"search-result-import-path\">projext/src/abstracts/cliCommand.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clicopyprojectfiles.js~clicopyprojectfilescommand",
    "class/src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand.html",
    "<span>CLICopyProjectFilesCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliCopyProjectFiles.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clirevision.js~clirevisioncommand",
    "class/src/services/cli/cliRevision.js~CLIRevisionCommand.html",
    "<span>CLIRevisionCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliRevision.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clirun.js~cliruncommand",
    "class/src/services/cli/cliRun.js~CLIRunCommand.html",
    "<span>CLIRunCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliRun.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clishbuild.js~clishbuildcommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html",
    "<span>CLISHBuildCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHBuild.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clishcopy.js~clishcopycommand",
    "class/src/services/cli/cliSHCopy.js~CLISHCopyCommand.html",
    "<span>CLISHCopyCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHCopy.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clishnoderun.js~clishnoderuncommand",
    "class/src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand.html",
    "<span>CLISHNodeRunCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHNodeRun.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clishrun.js~clishruncommand",
    "class/src/services/cli/cliSHRun.js~CLISHRunCommand.html",
    "<span>CLISHRunCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHRun.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clishtranspile.js~clishtranspilecommand",
    "class/src/services/cli/cliSHTranspile.js~CLISHTranspileCommand.html",
    "<span>CLISHTranspileCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHTranspile.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand",
    "class/src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand.html",
    "<span>CLISHValidateBuildCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHValidateBuild.js</span>",
    "class"
  ],
  [
    "projext/src/services/cli/clishvalidaterun.js~clishvalidateruncommand",
    "class/src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand.html",
    "<span>CLISHValidateRunCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHValidateRun.js</span>",
    "class"
  ],
  [
    "projext/src/services/common/cleaner.js~cleaner",
    "class/src/services/common/cleaner.js~Cleaner.html",
    "<span>Cleaner</span> <span class=\"search-result-import-path\">projext/src/services/common/cleaner.js</span>",
    "class"
  ],
  [
    "projext/src/abstracts/configurationfile.js~configurationfile",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html",
    "<span>ConfigurationFile</span> <span class=\"search-result-import-path\">projext/src/abstracts/configurationFile.js</span>",
    "class"
  ],
  [
    "projext/src/services/common/copier.js~copier",
    "class/src/services/common/copier.js~Copier.html",
    "<span>Copier</span> <span class=\"search-result-import-path\">projext/src/services/common/copier.js</span>",
    "class"
  ],
  [
    "projext/src/services/common/events.js~events",
    "class/src/services/common/events.js~Events.html",
    "<span>Events</span> <span class=\"search-result-import-path\">projext/src/services/common/events.js</span>",
    "class"
  ],
  [
    "projext/src/services/common/plugins.js~plugins",
    "class/src/services/common/plugins.js~Plugins.html",
    "<span>Plugins</span> <span class=\"search-result-import-path\">projext/src/services/common/plugins.js</span>",
    "class"
  ],
  [
    "projext/src/services/configurations/projectconfiguration.js~projectconfiguration",
    "class/src/services/configurations/projectConfiguration.js~ProjectConfiguration.html",
    "<span>ProjectConfiguration</span> <span class=\"search-result-import-path\">projext/src/services/configurations/projectConfiguration.js</span>",
    "class"
  ],
  [
    "projext/src/app/index.js~projext",
    "class/src/app/index.js~Projext.html",
    "<span>Projext</span> <span class=\"search-result-import-path\">projext/src/app/index.js</span>",
    "class"
  ],
  [
    "projext/src/services/configurations/targetconfiguration.js~targetconfiguration",
    "class/src/services/configurations/targetConfiguration.js~TargetConfiguration.html",
    "<span>TargetConfiguration</span> <span class=\"search-result-import-path\">projext/src/services/configurations/targetConfiguration.js</span>",
    "class"
  ],
  [
    "projext/src/services/building/targets.js~targets",
    "class/src/services/building/targets.js~Targets.html",
    "<span>Targets</span> <span class=\"search-result-import-path\">projext/src/services/building/targets.js</span>",
    "class"
  ],
  [
    "projext/src/services/common/versionutils.js~versionutils",
    "class/src/services/common/versionUtils.js~VersionUtils.html",
    "<span>VersionUtils</span> <span class=\"search-result-import-path\">projext/src/services/common/versionUtils.js</span>",
    "class"
  ],
  [
    "projext/src/services/configurations/babelconfiguration.js~babelconfiguration",
    "variable/index.html#static-variable-babelConfiguration",
    "<span>babelConfiguration</span> <span class=\"search-result-import-path\">projext/src/services/configurations/babelConfiguration.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/buildcleaner.js~buildcleaner",
    "variable/index.html#static-variable-buildCleaner",
    "<span>buildCleaner</span> <span class=\"search-result-import-path\">projext/src/services/building/buildCleaner.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/buildcopier.js~buildcopier",
    "variable/index.html#static-variable-buildCopier",
    "<span>buildCopier</span> <span class=\"search-result-import-path\">projext/src/services/building/buildCopier.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/buildengines.js~buildengines",
    "variable/index.html#static-variable-buildEngines",
    "<span>buildEngines</span> <span class=\"search-result-import-path\">projext/src/services/building/buildEngines.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/buildnoderunner.js~buildnoderunner",
    "variable/index.html#static-variable-buildNodeRunner",
    "<span>buildNodeRunner</span> <span class=\"search-result-import-path\">projext/src/services/building/buildNodeRunner.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess",
    "variable/index.html#static-variable-buildNodeRunnerProcess",
    "<span>buildNodeRunnerProcess</span> <span class=\"search-result-import-path\">projext/src/services/building/buildNodeRunnerProcess.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/buildtranspiler.js~buildtranspiler",
    "variable/index.html#static-variable-buildTranspiler",
    "<span>buildTranspiler</span> <span class=\"search-result-import-path\">projext/src/services/building/buildTranspiler.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/buildversion.js~buildversion",
    "variable/index.html#static-variable-buildVersion",
    "<span>buildVersion</span> <span class=\"search-result-import-path\">projext/src/services/building/buildVersion.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/builder.js~builder",
    "variable/index.html#static-variable-builder",
    "<span>builder</span> <span class=\"search-result-import-path\">projext/src/services/building/builder.js</span>",
    "variable"
  ],
  [
    "projext/src/services/common/cleaner.js~cleaner",
    "variable/index.html#static-variable-cleaner",
    "<span>cleaner</span> <span class=\"search-result-import-path\">projext/src/services/common/cleaner.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/cli.js~cli",
    "variable/index.html#static-variable-cli",
    "<span>cli</span> <span class=\"search-result-import-path\">projext/src/services/cli/cli.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clibuild.js~clibuildcommand",
    "variable/index.html#static-variable-cliBuildCommand",
    "<span>cliBuildCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliBuild.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/cliclean.js~clicleancommand",
    "variable/index.html#static-variable-cliCleanCommand",
    "<span>cliCleanCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliClean.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clicopyprojectfiles.js~clicopyprojectfilescommand",
    "variable/index.html#static-variable-cliCopyProjectFilesCommand",
    "<span>cliCopyProjectFilesCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliCopyProjectFiles.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clirevision.js~clirevisioncommand",
    "variable/index.html#static-variable-cliRevisionCommand",
    "<span>cliRevisionCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliRevision.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clirun.js~cliruncommand",
    "variable/index.html#static-variable-cliRunCommand",
    "<span>cliRunCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliRun.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clishbuild.js~clishbuildcommand",
    "variable/index.html#static-variable-cliSHBuildCommand",
    "<span>cliSHBuildCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHBuild.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clishcopy.js~clishcopycommand",
    "variable/index.html#static-variable-cliSHCopyCommand",
    "<span>cliSHCopyCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHCopy.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clishnoderun.js~clishnoderuncommand",
    "variable/index.html#static-variable-cliSHNodeRunCommand",
    "<span>cliSHNodeRunCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHNodeRun.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clishrun.js~clishruncommand",
    "variable/index.html#static-variable-cliSHRunCommand",
    "<span>cliSHRunCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHRun.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clishtranspile.js~clishtranspilecommand",
    "variable/index.html#static-variable-cliSHTranspileCommand",
    "<span>cliSHTranspileCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHTranspile.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand",
    "variable/index.html#static-variable-cliSHValidateBuildCommand",
    "<span>cliSHValidateBuildCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHValidateBuild.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/clishvalidaterun.js~clishvalidateruncommand",
    "variable/index.html#static-variable-cliSHValidateRunCommand",
    "<span>cliSHValidateRunCommand</span> <span class=\"search-result-import-path\">projext/src/services/cli/cliSHValidateRun.js</span>",
    "variable"
  ],
  [
    "projext/src/services/cli/cli.js~cliwithname",
    "function/index.html#static-function-cliWithName",
    "<span>cliWithName</span> <span class=\"search-result-import-path\">projext/src/services/cli/cli.js</span>",
    "function"
  ],
  [
    "projext/src/services/common/copier.js~copier",
    "variable/index.html#static-variable-copier",
    "<span>copier</span> <span class=\"search-result-import-path\">projext/src/services/common/copier.js</span>",
    "variable"
  ],
  [
    "projext/src/services/common/events.js~events",
    "variable/index.html#static-variable-events",
    "<span>events</span> <span class=\"search-result-import-path\">projext/src/services/common/events.js</span>",
    "variable"
  ],
  [
    "projext/src/services/common/plugins.js~plugins",
    "function/index.html#static-function-plugins",
    "<span>plugins</span> <span class=\"search-result-import-path\">projext/src/services/common/plugins.js</span>",
    "function"
  ],
  [
    "projext/src/services/configurations/projectconfiguration.js~projectconfiguration",
    "variable/index.html#static-variable-projectConfiguration",
    "<span>projectConfiguration</span> <span class=\"search-result-import-path\">projext/src/services/configurations/projectConfiguration.js</span>",
    "variable"
  ],
  [
    "projext/src/services/configurations/targetconfiguration.js~targetconfiguration",
    "variable/index.html#static-variable-targetConfiguration",
    "<span>targetConfiguration</span> <span class=\"search-result-import-path\">projext/src/services/configurations/targetConfiguration.js</span>",
    "variable"
  ],
  [
    "projext/src/services/building/targets.js~targets",
    "variable/index.html#static-variable-targets",
    "<span>targets</span> <span class=\"search-result-import-path\">projext/src/services/building/targets.js</span>",
    "variable"
  ],
  [
    "projext/src/services/common/versionutils.js~versionutils",
    "variable/index.html#static-variable-versionUtils",
    "<span>versionUtils</span> <span class=\"search-result-import-path\">projext/src/services/common/versionUtils.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/abstracts/clicommand.js",
    "file/src/abstracts/cliCommand.js.html",
    "src/abstracts/cliCommand.js",
    "file"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#addoption",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-method-addOption",
    "src/abstracts/cliCommand.js~CLICommand#addOption",
    "method"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#checkoptionsonparent",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-member-checkOptionsOnParent",
    "src/abstracts/cliCommand.js~CLICommand#checkOptionsOnParent",
    "member"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#cliname",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-member-cliName",
    "src/abstracts/cliCommand.js~CLICommand#cliName",
    "member"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#command",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-member-command",
    "src/abstracts/cliCommand.js~CLICommand#command",
    "member"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#constructor",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-constructor-constructor",
    "src/abstracts/cliCommand.js~CLICommand#constructor",
    "method"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#description",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-member-description",
    "src/abstracts/cliCommand.js~CLICommand#description",
    "member"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#generate",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-method-generate",
    "src/abstracts/cliCommand.js~CLICommand#generate",
    "method"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#handle",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-method-handle",
    "src/abstracts/cliCommand.js~CLICommand#handle",
    "method"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#hidden",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-member-hidden",
    "src/abstracts/cliCommand.js~CLICommand#hidden",
    "member"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#options",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-member-options",
    "src/abstracts/cliCommand.js~CLICommand#options",
    "member"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#optionsbyname",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-member-optionsByName",
    "src/abstracts/cliCommand.js~CLICommand#optionsByName",
    "member"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#output",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-method-output",
    "src/abstracts/cliCommand.js~CLICommand#output",
    "method"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#register",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-method-register",
    "src/abstracts/cliCommand.js~CLICommand#register",
    "method"
  ],
  [
    "src/abstracts/clicommand.js~clicommand#subprogram",
    "class/src/abstracts/cliCommand.js~CLICommand.html#instance-member-subProgram",
    "src/abstracts/cliCommand.js~CLICommand#subProgram",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js",
    "file/src/abstracts/configurationFile.js.html",
    "src/abstracts/configurationFile.js",
    "file"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#_config",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-_config",
    "src/abstracts/configurationFile.js~ConfigurationFile#_config",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#_fileconfig",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-_fileConfig",
    "src/abstracts/configurationFile.js~ConfigurationFile#_fileConfig",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#_fileconfigloaded",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-_fileConfigLoaded",
    "src/abstracts/configurationFile.js~ConfigurationFile#_fileConfigLoaded",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#asfactory",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-asFactory",
    "src/abstracts/configurationFile.js~ConfigurationFile#asFactory",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#constructor",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-constructor-constructor",
    "src/abstracts/configurationFile.js~ConfigurationFile#constructor",
    "method"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#createconfig",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-method-createConfig",
    "src/abstracts/configurationFile.js~ConfigurationFile#createConfig",
    "method"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#getconfig",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-method-getConfig",
    "src/abstracts/configurationFile.js~ConfigurationFile#getConfig",
    "method"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#overwritepath",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-overwritePath",
    "src/abstracts/configurationFile.js~ConfigurationFile#overwritePath",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#parentconfig",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-parentConfig",
    "src/abstracts/configurationFile.js~ConfigurationFile#parentConfig",
    "member"
  ],
  [
    "src/abstracts/configurationfile.js~configurationfile#pathutils",
    "class/src/abstracts/configurationFile.js~ConfigurationFile.html#instance-member-pathUtils",
    "src/abstracts/configurationFile.js~ConfigurationFile#pathUtils",
    "member"
  ],
  [
    "src/app/index.js",
    "file/src/app/index.js.html",
    "src/app/index.js",
    "file"
  ],
  [
    "src/app/index.js~projext#cli",
    "class/src/app/index.js~Projext.html#instance-method-cli",
    "src/app/index.js~Projext#cli",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/services/building/buildcleaner.js",
    "file/src/services/building/buildCleaner.js.html",
    "src/services/building/buildCleaner.js",
    "file"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#applogger",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-member-appLogger",
    "src/services/building/buildCleaner.js~BuildCleaner#appLogger",
    "member"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#cleanall",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-method-cleanAll",
    "src/services/building/buildCleaner.js~BuildCleaner#cleanAll",
    "method"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#cleanbrowsertarget",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-method-cleanBrowserTarget",
    "src/services/building/buildCleaner.js~BuildCleaner#cleanBrowserTarget",
    "method"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#cleannodetarget",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-method-cleanNodeTarget",
    "src/services/building/buildCleaner.js~BuildCleaner#cleanNodeTarget",
    "method"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#cleantarget",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-method-cleanTarget",
    "src/services/building/buildCleaner.js~BuildCleaner#cleanTarget",
    "method"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#cleaner",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-member-cleaner",
    "src/services/building/buildCleaner.js~BuildCleaner#cleaner",
    "member"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#constructor",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-constructor-constructor",
    "src/services/building/buildCleaner.js~BuildCleaner#constructor",
    "method"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#gettargetnamesvariation",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-method-getTargetNamesVariation",
    "src/services/building/buildCleaner.js~BuildCleaner#getTargetNamesVariation",
    "method"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#pathutils",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-member-pathUtils",
    "src/services/building/buildCleaner.js~BuildCleaner#pathUtils",
    "member"
  ],
  [
    "src/services/building/buildcleaner.js~buildcleaner#projectconfiguration",
    "class/src/services/building/buildCleaner.js~BuildCleaner.html#instance-member-projectConfiguration",
    "src/services/building/buildCleaner.js~BuildCleaner#projectConfiguration",
    "member"
  ],
  [
    "src/services/building/buildcopier.js",
    "file/src/services/building/buildCopier.js.html",
    "src/services/building/buildCopier.js",
    "file"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#addprivatemodules",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-method-addPrivateModules",
    "src/services/building/buildCopier.js~BuildCopier#addPrivateModules",
    "method"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#applogger",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-member-appLogger",
    "src/services/building/buildCopier.js~BuildCopier#appLogger",
    "member"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#constructor",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-constructor-constructor",
    "src/services/building/buildCopier.js~BuildCopier#constructor",
    "method"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#copier",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-member-copier",
    "src/services/building/buildCopier.js~BuildCopier#copier",
    "member"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#copyfiles",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-method-copyFiles",
    "src/services/building/buildCopier.js~BuildCopier#copyFiles",
    "method"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#copytargetfiles",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-method-copyTargetFiles",
    "src/services/building/buildCopier.js~BuildCopier#copyTargetFiles",
    "method"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#events",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-member-events",
    "src/services/building/buildCopier.js~BuildCopier#events",
    "member"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#pathutils",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-member-pathUtils",
    "src/services/building/buildCopier.js~BuildCopier#pathUtils",
    "member"
  ],
  [
    "src/services/building/buildcopier.js~buildcopier#projectconfiguration",
    "class/src/services/building/buildCopier.js~BuildCopier.html#instance-member-projectConfiguration",
    "src/services/building/buildCopier.js~BuildCopier#projectConfiguration",
    "member"
  ],
  [
    "src/services/building/buildengines.js",
    "file/src/services/building/buildEngines.js.html",
    "src/services/building/buildEngines.js",
    "file"
  ],
  [
    "src/services/building/buildengines.js~buildengines#app",
    "class/src/services/building/buildEngines.js~BuildEngines.html#instance-member-app",
    "src/services/building/buildEngines.js~BuildEngines#app",
    "member"
  ],
  [
    "src/services/building/buildengines.js~buildengines#constructor",
    "class/src/services/building/buildEngines.js~BuildEngines.html#instance-constructor-constructor",
    "src/services/building/buildEngines.js~BuildEngines#constructor",
    "method"
  ],
  [
    "src/services/building/buildengines.js~buildengines#getengine",
    "class/src/services/building/buildEngines.js~BuildEngines.html#instance-method-getEngine",
    "src/services/building/buildEngines.js~BuildEngines#getEngine",
    "method"
  ],
  [
    "src/services/building/buildnoderunner.js",
    "file/src/services/building/buildNodeRunner.js.html",
    "src/services/building/buildNodeRunner.js",
    "file"
  ],
  [
    "src/services/building/buildnoderunner.js~buildnoderunner#_run",
    "class/src/services/building/buildNodeRunner.js~BuildNodeRunner.html#instance-method-_run",
    "src/services/building/buildNodeRunner.js~BuildNodeRunner#_run",
    "method"
  ],
  [
    "src/services/building/buildnoderunner.js~buildnoderunner#_runwithtranspilation",
    "class/src/services/building/buildNodeRunner.js~BuildNodeRunner.html#instance-method-_runWithTranspilation",
    "src/services/building/buildNodeRunner.js~BuildNodeRunner#_runWithTranspilation",
    "method"
  ],
  [
    "src/services/building/buildnoderunner.js~buildnoderunner#buildnoderunnerprocess",
    "class/src/services/building/buildNodeRunner.js~BuildNodeRunner.html#instance-member-buildNodeRunnerProcess",
    "src/services/building/buildNodeRunner.js~BuildNodeRunner#buildNodeRunnerProcess",
    "member"
  ],
  [
    "src/services/building/buildnoderunner.js~buildnoderunner#constructor",
    "class/src/services/building/buildNodeRunner.js~BuildNodeRunner.html#instance-constructor-constructor",
    "src/services/building/buildNodeRunner.js~BuildNodeRunner#constructor",
    "method"
  ],
  [
    "src/services/building/buildnoderunner.js~buildnoderunner#runtarget",
    "class/src/services/building/buildNodeRunner.js~BuildNodeRunner.html#instance-method-runTarget",
    "src/services/building/buildNodeRunner.js~BuildNodeRunner#runTarget",
    "method"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js",
    "file/src/services/building/buildNodeRunnerProcess.js.html",
    "src/services/building/buildNodeRunnerProcess.js",
    "file"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess#applogger",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html#instance-member-appLogger",
    "src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess#appLogger",
    "member"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess#buildtranspiler",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html#instance-member-buildTranspiler",
    "src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess#buildTranspiler",
    "member"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess#constructor",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html#instance-constructor-constructor",
    "src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess#constructor",
    "method"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess#defaultoptions",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html#instance-member-defaultOptions",
    "src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess#defaultOptions",
    "member"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess#options",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html#instance-member-options",
    "src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess#options",
    "member"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess#run",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html#instance-method-run",
    "src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess#run",
    "method"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess#running",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html#instance-member-running",
    "src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess#running",
    "member"
  ],
  [
    "src/services/building/buildnoderunnerprocess.js~buildnoderunnerprocess#watcher",
    "class/src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess.html#instance-member-watcher",
    "src/services/building/buildNodeRunnerProcess.js~BuildNodeRunnerProcess#watcher",
    "member"
  ],
  [
    "src/services/building/buildtranspiler.js",
    "file/src/services/building/buildTranspiler.js.html",
    "src/services/building/buildTranspiler.js",
    "file"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#applogger",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-member-appLogger",
    "src/services/building/buildTranspiler.js~BuildTranspiler#appLogger",
    "member"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#babelconfiguration",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-member-babelConfiguration",
    "src/services/building/buildTranspiler.js~BuildTranspiler#babelConfiguration",
    "member"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#constructor",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-constructor-constructor",
    "src/services/building/buildTranspiler.js~BuildTranspiler#constructor",
    "method"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#findfiles",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-method-findFiles",
    "src/services/building/buildTranspiler.js~BuildTranspiler#findFiles",
    "method"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#gettargetconfigurationforfile",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-method-getTargetConfigurationForFile",
    "src/services/building/buildTranspiler.js~BuildTranspiler#getTargetConfigurationForFile",
    "method"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#pathutils",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-member-pathUtils",
    "src/services/building/buildTranspiler.js~BuildTranspiler#pathUtils",
    "member"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#projectconfiguration",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-member-projectConfiguration",
    "src/services/building/buildTranspiler.js~BuildTranspiler#projectConfiguration",
    "member"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#targets",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-member-targets",
    "src/services/building/buildTranspiler.js~BuildTranspiler#targets",
    "member"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#transpilefile",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-method-transpileFile",
    "src/services/building/buildTranspiler.js~BuildTranspiler#transpileFile",
    "method"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#transpilefilesync",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-method-transpileFileSync",
    "src/services/building/buildTranspiler.js~BuildTranspiler#transpileFileSync",
    "method"
  ],
  [
    "src/services/building/buildtranspiler.js~buildtranspiler#transpiletargetfiles",
    "class/src/services/building/buildTranspiler.js~BuildTranspiler.html#instance-method-transpileTargetFiles",
    "src/services/building/buildTranspiler.js~BuildTranspiler#transpileTargetFiles",
    "method"
  ],
  [
    "src/services/building/buildversion.js",
    "file/src/services/building/buildVersion.js.html",
    "src/services/building/buildVersion.js",
    "file"
  ],
  [
    "src/services/building/buildversion.js~buildversion#constructor",
    "class/src/services/building/buildVersion.js~BuildVersion.html#instance-constructor-constructor",
    "src/services/building/buildVersion.js~BuildVersion#constructor",
    "method"
  ],
  [
    "src/services/building/buildversion.js~buildversion#createrevision",
    "class/src/services/building/buildVersion.js~BuildVersion.html#instance-method-createRevision",
    "src/services/building/buildVersion.js~BuildVersion#createRevision",
    "method"
  ],
  [
    "src/services/building/buildversion.js~buildversion#events",
    "class/src/services/building/buildVersion.js~BuildVersion.html#instance-member-events",
    "src/services/building/buildVersion.js~BuildVersion#events",
    "member"
  ],
  [
    "src/services/building/buildversion.js~buildversion#getdefinitionvariable",
    "class/src/services/building/buildVersion.js~BuildVersion.html#instance-method-getDefinitionVariable",
    "src/services/building/buildVersion.js~BuildVersion#getDefinitionVariable",
    "method"
  ],
  [
    "src/services/building/buildversion.js~buildversion#getversion",
    "class/src/services/building/buildVersion.js~BuildVersion.html#instance-method-getVersion",
    "src/services/building/buildVersion.js~BuildVersion#getVersion",
    "method"
  ],
  [
    "src/services/building/buildversion.js~buildversion#projectconfiguration",
    "class/src/services/building/buildVersion.js~BuildVersion.html#instance-member-projectConfiguration",
    "src/services/building/buildVersion.js~BuildVersion#projectConfiguration",
    "member"
  ],
  [
    "src/services/building/buildversion.js~buildversion#versionutils",
    "class/src/services/building/buildVersion.js~BuildVersion.html#instance-member-versionUtils",
    "src/services/building/buildVersion.js~BuildVersion#versionUtils",
    "member"
  ],
  [
    "src/services/building/builder.js",
    "file/src/services/building/builder.js.html",
    "src/services/building/builder.js",
    "file"
  ],
  [
    "src/services/building/builder.js~builder#buildcleaner",
    "class/src/services/building/builder.js~Builder.html#instance-member-buildCleaner",
    "src/services/building/builder.js~Builder#buildCleaner",
    "member"
  ],
  [
    "src/services/building/builder.js~builder#buildcopier",
    "class/src/services/building/builder.js~Builder.html#instance-member-buildCopier",
    "src/services/building/builder.js~Builder#buildCopier",
    "member"
  ],
  [
    "src/services/building/builder.js~builder#buildengines",
    "class/src/services/building/builder.js~Builder.html#instance-member-buildEngines",
    "src/services/building/builder.js~Builder#buildEngines",
    "member"
  ],
  [
    "src/services/building/builder.js~builder#buildtranspiler",
    "class/src/services/building/builder.js~Builder.html#instance-member-buildTranspiler",
    "src/services/building/builder.js~Builder#buildTranspiler",
    "member"
  ],
  [
    "src/services/building/builder.js~builder#cleantarget",
    "class/src/services/building/builder.js~Builder.html#instance-method-cleanTarget",
    "src/services/building/builder.js~Builder#cleanTarget",
    "method"
  ],
  [
    "src/services/building/builder.js~builder#constructor",
    "class/src/services/building/builder.js~Builder.html#instance-constructor-constructor",
    "src/services/building/builder.js~Builder#constructor",
    "method"
  ],
  [
    "src/services/building/builder.js~builder#copytarget",
    "class/src/services/building/builder.js~Builder.html#instance-method-copyTarget",
    "src/services/building/builder.js~Builder#copyTarget",
    "method"
  ],
  [
    "src/services/building/builder.js~builder#gettargetbuildcommand",
    "class/src/services/building/builder.js~Builder.html#instance-method-getTargetBuildCommand",
    "src/services/building/builder.js~Builder#getTargetBuildCommand",
    "method"
  ],
  [
    "src/services/building/builder.js~builder#targets",
    "class/src/services/building/builder.js~Builder.html#instance-member-targets",
    "src/services/building/builder.js~Builder#targets",
    "member"
  ],
  [
    "src/services/building/builder.js~builder#transpiletarget",
    "class/src/services/building/builder.js~Builder.html#instance-method-transpileTarget",
    "src/services/building/builder.js~Builder#transpileTarget",
    "method"
  ],
  [
    "src/services/building/index.js",
    "file/src/services/building/index.js.html",
    "src/services/building/index.js",
    "file"
  ],
  [
    "src/services/building/targets.js",
    "file/src/services/building/targets.js.html",
    "src/services/building/targets.js",
    "file"
  ],
  [
    "src/services/building/targets.js~targets#constructor",
    "class/src/services/building/targets.js~Targets.html#instance-constructor-constructor",
    "src/services/building/targets.js~Targets#constructor",
    "method"
  ],
  [
    "src/services/building/targets.js~targets#defaulttype",
    "class/src/services/building/targets.js~Targets.html#instance-member-defaultType",
    "src/services/building/targets.js~Targets#defaultType",
    "member"
  ],
  [
    "src/services/building/targets.js~targets#environmentutils",
    "class/src/services/building/targets.js~Targets.html#instance-member-environmentUtils",
    "src/services/building/targets.js~Targets#environmentUtils",
    "member"
  ],
  [
    "src/services/building/targets.js~targets#events",
    "class/src/services/building/targets.js~Targets.html#instance-member-events",
    "src/services/building/targets.js~Targets#events",
    "member"
  ],
  [
    "src/services/building/targets.js~targets#findtargetforfile",
    "class/src/services/building/targets.js~Targets.html#instance-method-findTargetForFile",
    "src/services/building/targets.js~Targets#findTargetForFile",
    "method"
  ],
  [
    "src/services/building/targets.js~targets#getbrowsertargetconfiguration",
    "class/src/services/building/targets.js~Targets.html#instance-method-getBrowserTargetConfiguration",
    "src/services/building/targets.js~Targets#getBrowserTargetConfiguration",
    "method"
  ],
  [
    "src/services/building/targets.js~targets#gettarget",
    "class/src/services/building/targets.js~Targets.html#instance-method-getTarget",
    "src/services/building/targets.js~Targets#getTarget",
    "method"
  ],
  [
    "src/services/building/targets.js~targets#gettargets",
    "class/src/services/building/targets.js~Targets.html#instance-method-getTargets",
    "src/services/building/targets.js~Targets#getTargets",
    "method"
  ],
  [
    "src/services/building/targets.js~targets#loadtargets",
    "class/src/services/building/targets.js~Targets.html#instance-method-loadTargets",
    "src/services/building/targets.js~Targets#loadTargets",
    "method"
  ],
  [
    "src/services/building/targets.js~targets#pathutils",
    "class/src/services/building/targets.js~Targets.html#instance-member-pathUtils",
    "src/services/building/targets.js~Targets#pathUtils",
    "member"
  ],
  [
    "src/services/building/targets.js~targets#projectconfiguration",
    "class/src/services/building/targets.js~Targets.html#instance-member-projectConfiguration",
    "src/services/building/targets.js~Targets#projectConfiguration",
    "member"
  ],
  [
    "src/services/building/targets.js~targets#rootrequire",
    "class/src/services/building/targets.js~Targets.html#instance-member-rootRequire",
    "src/services/building/targets.js~Targets#rootRequire",
    "member"
  ],
  [
    "src/services/building/targets.js~targets#targets",
    "class/src/services/building/targets.js~Targets.html#instance-member-targets",
    "src/services/building/targets.js~Targets#targets",
    "member"
  ],
  [
    "src/services/building/targets.js~targets#typesvalidationregex",
    "class/src/services/building/targets.js~Targets.html#instance-member-typesValidationRegex",
    "src/services/building/targets.js~Targets#typesValidationRegex",
    "member"
  ],
  [
    "src/services/cli/cli.js",
    "file/src/services/cli/cli.js.html",
    "src/services/cli/cli.js",
    "file"
  ],
  [
    "src/services/cli/cli.js~cli#constructor",
    "class/src/services/cli/cli.js~CLI.html#instance-constructor-constructor",
    "src/services/cli/cli.js~CLI#constructor",
    "method"
  ],
  [
    "src/services/cli/cli.js~cli#info",
    "class/src/services/cli/cli.js~CLI.html#instance-member-info",
    "src/services/cli/cli.js~CLI#info",
    "member"
  ],
  [
    "src/services/cli/cli.js~cli#name",
    "class/src/services/cli/cli.js~CLI.html#instance-member-name",
    "src/services/cli/cli.js~CLI#name",
    "member"
  ],
  [
    "src/services/cli/cli.js~cli#start",
    "class/src/services/cli/cli.js~CLI.html#instance-method-start",
    "src/services/cli/cli.js~CLI#start",
    "method"
  ],
  [
    "src/services/cli/clibuild.js",
    "file/src/services/cli/cliBuild.js.html",
    "src/services/cli/cliBuild.js",
    "file"
  ],
  [
    "src/services/cli/clibuild.js~clibuildcommand#command",
    "class/src/services/cli/cliBuild.js~CLIBuildCommand.html#instance-member-command",
    "src/services/cli/cliBuild.js~CLIBuildCommand#command",
    "member"
  ],
  [
    "src/services/cli/clibuild.js~clibuildcommand#constructor",
    "class/src/services/cli/cliBuild.js~CLIBuildCommand.html#instance-constructor-constructor",
    "src/services/cli/cliBuild.js~CLIBuildCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clibuild.js~clibuildcommand#description",
    "class/src/services/cli/cliBuild.js~CLIBuildCommand.html#instance-member-description",
    "src/services/cli/cliBuild.js~CLIBuildCommand#description",
    "member"
  ],
  [
    "src/services/cli/cliclean.js",
    "file/src/services/cli/cliClean.js.html",
    "src/services/cli/cliClean.js",
    "file"
  ],
  [
    "src/services/cli/cliclean.js~clicleancommand#buildcleaner",
    "class/src/services/cli/cliClean.js~CLICleanCommand.html#instance-member-buildCleaner",
    "src/services/cli/cliClean.js~CLICleanCommand#buildCleaner",
    "member"
  ],
  [
    "src/services/cli/cliclean.js~clicleancommand#builder",
    "class/src/services/cli/cliClean.js~CLICleanCommand.html#instance-member-builder",
    "src/services/cli/cliClean.js~CLICleanCommand#builder",
    "member"
  ],
  [
    "src/services/cli/cliclean.js~clicleancommand#command",
    "class/src/services/cli/cliClean.js~CLICleanCommand.html#instance-member-command",
    "src/services/cli/cliClean.js~CLICleanCommand#command",
    "member"
  ],
  [
    "src/services/cli/cliclean.js~clicleancommand#constructor",
    "class/src/services/cli/cliClean.js~CLICleanCommand.html#instance-constructor-constructor",
    "src/services/cli/cliClean.js~CLICleanCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/cliclean.js~clicleancommand#description",
    "class/src/services/cli/cliClean.js~CLICleanCommand.html#instance-member-description",
    "src/services/cli/cliClean.js~CLICleanCommand#description",
    "member"
  ],
  [
    "src/services/cli/cliclean.js~clicleancommand#handle",
    "class/src/services/cli/cliClean.js~CLICleanCommand.html#instance-method-handle",
    "src/services/cli/cliClean.js~CLICleanCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clicopyprojectfiles.js",
    "file/src/services/cli/cliCopyProjectFiles.js.html",
    "src/services/cli/cliCopyProjectFiles.js",
    "file"
  ],
  [
    "src/services/cli/clicopyprojectfiles.js~clicopyprojectfilescommand#buildcopier",
    "class/src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand.html#instance-member-buildCopier",
    "src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand#buildCopier",
    "member"
  ],
  [
    "src/services/cli/clicopyprojectfiles.js~clicopyprojectfilescommand#command",
    "class/src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand.html#instance-member-command",
    "src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand#command",
    "member"
  ],
  [
    "src/services/cli/clicopyprojectfiles.js~clicopyprojectfilescommand#constructor",
    "class/src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand.html#instance-constructor-constructor",
    "src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clicopyprojectfiles.js~clicopyprojectfilescommand#description",
    "class/src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand.html#instance-member-description",
    "src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand#description",
    "member"
  ],
  [
    "src/services/cli/clicopyprojectfiles.js~clicopyprojectfilescommand#handle",
    "class/src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand.html#instance-method-handle",
    "src/services/cli/cliCopyProjectFiles.js~CLICopyProjectFilesCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clirevision.js",
    "file/src/services/cli/cliRevision.js.html",
    "src/services/cli/cliRevision.js",
    "file"
  ],
  [
    "src/services/cli/clirevision.js~clirevisioncommand#buildversion",
    "class/src/services/cli/cliRevision.js~CLIRevisionCommand.html#instance-member-buildVersion",
    "src/services/cli/cliRevision.js~CLIRevisionCommand#buildVersion",
    "member"
  ],
  [
    "src/services/cli/clirevision.js~clirevisioncommand#command",
    "class/src/services/cli/cliRevision.js~CLIRevisionCommand.html#instance-member-command",
    "src/services/cli/cliRevision.js~CLIRevisionCommand#command",
    "member"
  ],
  [
    "src/services/cli/clirevision.js~clirevisioncommand#constructor",
    "class/src/services/cli/cliRevision.js~CLIRevisionCommand.html#instance-constructor-constructor",
    "src/services/cli/cliRevision.js~CLIRevisionCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clirevision.js~clirevisioncommand#description",
    "class/src/services/cli/cliRevision.js~CLIRevisionCommand.html#instance-member-description",
    "src/services/cli/cliRevision.js~CLIRevisionCommand#description",
    "member"
  ],
  [
    "src/services/cli/clirevision.js~clirevisioncommand#handle",
    "class/src/services/cli/cliRevision.js~CLIRevisionCommand.html#instance-method-handle",
    "src/services/cli/cliRevision.js~CLIRevisionCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clirun.js",
    "file/src/services/cli/cliRun.js.html",
    "src/services/cli/cliRun.js",
    "file"
  ],
  [
    "src/services/cli/clirun.js~cliruncommand#command",
    "class/src/services/cli/cliRun.js~CLIRunCommand.html#instance-member-command",
    "src/services/cli/cliRun.js~CLIRunCommand#command",
    "member"
  ],
  [
    "src/services/cli/clirun.js~cliruncommand#description",
    "class/src/services/cli/cliRun.js~CLIRunCommand.html#instance-member-description",
    "src/services/cli/cliRun.js~CLIRunCommand#description",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js",
    "file/src/services/cli/cliSHBuild.js.html",
    "src/services/cli/cliSHBuild.js",
    "file"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#builder",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-builder",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#builder",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#clicleancommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-cliCleanCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#cliCleanCommand",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#clicopyprojectfilescommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-cliCopyProjectFilesCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#cliCopyProjectFilesCommand",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#clirevisioncommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-cliRevisionCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#cliRevisionCommand",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#clishcopycommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-cliSHCopyCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#cliSHCopyCommand",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#clishnoderuncommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-cliSHNodeRunCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#cliSHNodeRunCommand",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#clishtranspilecommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-cliSHTranspileCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#cliSHTranspileCommand",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#command",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-command",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#command",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#constructor",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-constructor-constructor",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#description",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-description",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#description",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#events",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-events",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#events",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#getbuildcommandifneeded",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getBuildCommandIfNeeded",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getBuildCommandIfNeeded",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#getcleancommandifneeded",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getCleanCommandIfNeeded",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getCleanCommandIfNeeded",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#getcommandsforbrowsertarget",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getCommandsForBrowserTarget",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getCommandsForBrowserTarget",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#getcommandsfornodetarget",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getCommandsForNodeTarget",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getCommandsForNodeTarget",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#getcopycommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getCopyCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getCopyCommand",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#getcopyprojectfilescommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getCopyProjectFilesCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getCopyProjectFilesCommand",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#getnoderuncommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getNodeRunCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getNodeRunCommand",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#getrevisioncommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getRevisionCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getRevisionCommand",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#gettranspilecommand",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-getTranspileCommand",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#getTranspileCommand",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#handle",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-method-handle",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#hidden",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-hidden",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#hidden",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#projectconfiguration",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-projectConfiguration",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#projectConfiguration",
    "member"
  ],
  [
    "src/services/cli/clishbuild.js~clishbuildcommand#targets",
    "class/src/services/cli/cliSHBuild.js~CLISHBuildCommand.html#instance-member-targets",
    "src/services/cli/cliSHBuild.js~CLISHBuildCommand#targets",
    "member"
  ],
  [
    "src/services/cli/clishcopy.js",
    "file/src/services/cli/cliSHCopy.js.html",
    "src/services/cli/cliSHCopy.js",
    "file"
  ],
  [
    "src/services/cli/clishcopy.js~clishcopycommand#builder",
    "class/src/services/cli/cliSHCopy.js~CLISHCopyCommand.html#instance-member-builder",
    "src/services/cli/cliSHCopy.js~CLISHCopyCommand#builder",
    "member"
  ],
  [
    "src/services/cli/clishcopy.js~clishcopycommand#command",
    "class/src/services/cli/cliSHCopy.js~CLISHCopyCommand.html#instance-member-command",
    "src/services/cli/cliSHCopy.js~CLISHCopyCommand#command",
    "member"
  ],
  [
    "src/services/cli/clishcopy.js~clishcopycommand#constructor",
    "class/src/services/cli/cliSHCopy.js~CLISHCopyCommand.html#instance-constructor-constructor",
    "src/services/cli/cliSHCopy.js~CLISHCopyCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clishcopy.js~clishcopycommand#description",
    "class/src/services/cli/cliSHCopy.js~CLISHCopyCommand.html#instance-member-description",
    "src/services/cli/cliSHCopy.js~CLISHCopyCommand#description",
    "member"
  ],
  [
    "src/services/cli/clishcopy.js~clishcopycommand#handle",
    "class/src/services/cli/cliSHCopy.js~CLISHCopyCommand.html#instance-method-handle",
    "src/services/cli/cliSHCopy.js~CLISHCopyCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clishcopy.js~clishcopycommand#hidden",
    "class/src/services/cli/cliSHCopy.js~CLISHCopyCommand.html#instance-member-hidden",
    "src/services/cli/cliSHCopy.js~CLISHCopyCommand#hidden",
    "member"
  ],
  [
    "src/services/cli/clishnoderun.js",
    "file/src/services/cli/cliSHNodeRun.js.html",
    "src/services/cli/cliSHNodeRun.js",
    "file"
  ],
  [
    "src/services/cli/clishnoderun.js~clishnoderuncommand#buildnoderunner",
    "class/src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand.html#instance-member-buildNodeRunner",
    "src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand#buildNodeRunner",
    "member"
  ],
  [
    "src/services/cli/clishnoderun.js~clishnoderuncommand#command",
    "class/src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand.html#instance-member-command",
    "src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand#command",
    "member"
  ],
  [
    "src/services/cli/clishnoderun.js~clishnoderuncommand#constructor",
    "class/src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand.html#instance-constructor-constructor",
    "src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clishnoderun.js~clishnoderuncommand#description",
    "class/src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand.html#instance-member-description",
    "src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand#description",
    "member"
  ],
  [
    "src/services/cli/clishnoderun.js~clishnoderuncommand#handle",
    "class/src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand.html#instance-method-handle",
    "src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clishnoderun.js~clishnoderuncommand#hidden",
    "class/src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand.html#instance-member-hidden",
    "src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand#hidden",
    "member"
  ],
  [
    "src/services/cli/clishnoderun.js~clishnoderuncommand#targets",
    "class/src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand.html#instance-member-targets",
    "src/services/cli/cliSHNodeRun.js~CLISHNodeRunCommand#targets",
    "member"
  ],
  [
    "src/services/cli/clishrun.js",
    "file/src/services/cli/cliSHRun.js.html",
    "src/services/cli/cliSHRun.js",
    "file"
  ],
  [
    "src/services/cli/clishrun.js~clishruncommand#clibuildcommand",
    "class/src/services/cli/cliSHRun.js~CLISHRunCommand.html#instance-member-cliBuildCommand",
    "src/services/cli/cliSHRun.js~CLISHRunCommand#cliBuildCommand",
    "member"
  ],
  [
    "src/services/cli/clishrun.js~clishruncommand#command",
    "class/src/services/cli/cliSHRun.js~CLISHRunCommand.html#instance-member-command",
    "src/services/cli/cliSHRun.js~CLISHRunCommand#command",
    "member"
  ],
  [
    "src/services/cli/clishrun.js~clishruncommand#constructor",
    "class/src/services/cli/cliSHRun.js~CLISHRunCommand.html#instance-constructor-constructor",
    "src/services/cli/cliSHRun.js~CLISHRunCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clishrun.js~clishruncommand#description",
    "class/src/services/cli/cliSHRun.js~CLISHRunCommand.html#instance-member-description",
    "src/services/cli/cliSHRun.js~CLISHRunCommand#description",
    "member"
  ],
  [
    "src/services/cli/clishrun.js~clishruncommand#handle",
    "class/src/services/cli/cliSHRun.js~CLISHRunCommand.html#instance-method-handle",
    "src/services/cli/cliSHRun.js~CLISHRunCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clishrun.js~clishruncommand#hidden",
    "class/src/services/cli/cliSHRun.js~CLISHRunCommand.html#instance-member-hidden",
    "src/services/cli/cliSHRun.js~CLISHRunCommand#hidden",
    "member"
  ],
  [
    "src/services/cli/clishtranspile.js",
    "file/src/services/cli/cliSHTranspile.js.html",
    "src/services/cli/cliSHTranspile.js",
    "file"
  ],
  [
    "src/services/cli/clishtranspile.js~clishtranspilecommand#builder",
    "class/src/services/cli/cliSHTranspile.js~CLISHTranspileCommand.html#instance-member-builder",
    "src/services/cli/cliSHTranspile.js~CLISHTranspileCommand#builder",
    "member"
  ],
  [
    "src/services/cli/clishtranspile.js~clishtranspilecommand#command",
    "class/src/services/cli/cliSHTranspile.js~CLISHTranspileCommand.html#instance-member-command",
    "src/services/cli/cliSHTranspile.js~CLISHTranspileCommand#command",
    "member"
  ],
  [
    "src/services/cli/clishtranspile.js~clishtranspilecommand#constructor",
    "class/src/services/cli/cliSHTranspile.js~CLISHTranspileCommand.html#instance-constructor-constructor",
    "src/services/cli/cliSHTranspile.js~CLISHTranspileCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clishtranspile.js~clishtranspilecommand#description",
    "class/src/services/cli/cliSHTranspile.js~CLISHTranspileCommand.html#instance-member-description",
    "src/services/cli/cliSHTranspile.js~CLISHTranspileCommand#description",
    "member"
  ],
  [
    "src/services/cli/clishtranspile.js~clishtranspilecommand#handle",
    "class/src/services/cli/cliSHTranspile.js~CLISHTranspileCommand.html#instance-method-handle",
    "src/services/cli/cliSHTranspile.js~CLISHTranspileCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clishtranspile.js~clishtranspilecommand#hidden",
    "class/src/services/cli/cliSHTranspile.js~CLISHTranspileCommand.html#instance-member-hidden",
    "src/services/cli/cliSHTranspile.js~CLISHTranspileCommand#hidden",
    "member"
  ],
  [
    "src/services/cli/clishvalidatebuild.js",
    "file/src/services/cli/cliSHValidateBuild.js.html",
    "src/services/cli/cliSHValidateBuild.js",
    "file"
  ],
  [
    "src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand#applogger",
    "class/src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand.html#instance-member-appLogger",
    "src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand#appLogger",
    "member"
  ],
  [
    "src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand#command",
    "class/src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand.html#instance-member-command",
    "src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand#command",
    "member"
  ],
  [
    "src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand#constructor",
    "class/src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand.html#instance-constructor-constructor",
    "src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand#description",
    "class/src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand.html#instance-member-description",
    "src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand#description",
    "member"
  ],
  [
    "src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand#handle",
    "class/src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand.html#instance-method-handle",
    "src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand#hidden",
    "class/src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand.html#instance-member-hidden",
    "src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand#hidden",
    "member"
  ],
  [
    "src/services/cli/clishvalidatebuild.js~clishvalidatebuildcommand#targets",
    "class/src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand.html#instance-member-targets",
    "src/services/cli/cliSHValidateBuild.js~CLISHValidateBuildCommand#targets",
    "member"
  ],
  [
    "src/services/cli/clishvalidaterun.js",
    "file/src/services/cli/cliSHValidateRun.js.html",
    "src/services/cli/cliSHValidateRun.js",
    "file"
  ],
  [
    "src/services/cli/clishvalidaterun.js~clishvalidateruncommand#command",
    "class/src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand.html#instance-member-command",
    "src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand#command",
    "member"
  ],
  [
    "src/services/cli/clishvalidaterun.js~clishvalidateruncommand#constructor",
    "class/src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand.html#instance-constructor-constructor",
    "src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand#constructor",
    "method"
  ],
  [
    "src/services/cli/clishvalidaterun.js~clishvalidateruncommand#description",
    "class/src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand.html#instance-member-description",
    "src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand#description",
    "member"
  ],
  [
    "src/services/cli/clishvalidaterun.js~clishvalidateruncommand#handle",
    "class/src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand.html#instance-method-handle",
    "src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand#handle",
    "method"
  ],
  [
    "src/services/cli/clishvalidaterun.js~clishvalidateruncommand#hidden",
    "class/src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand.html#instance-member-hidden",
    "src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand#hidden",
    "member"
  ],
  [
    "src/services/cli/clishvalidaterun.js~clishvalidateruncommand#targets",
    "class/src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand.html#instance-member-targets",
    "src/services/cli/cliSHValidateRun.js~CLISHValidateRunCommand#targets",
    "member"
  ],
  [
    "src/services/cli/index.js",
    "file/src/services/cli/index.js.html",
    "src/services/cli/index.js",
    "file"
  ],
  [
    "src/services/common/cleaner.js",
    "file/src/services/common/cleaner.js.html",
    "src/services/common/cleaner.js",
    "file"
  ],
  [
    "src/services/common/cleaner.js~cleaner.clean",
    "class/src/services/common/cleaner.js~Cleaner.html#static-method-clean",
    "src/services/common/cleaner.js~Cleaner.clean",
    "method"
  ],
  [
    "src/services/common/copier.js",
    "file/src/services/common/copier.js.html",
    "src/services/common/copier.js",
    "file"
  ],
  [
    "src/services/common/copier.js~copier.copy",
    "class/src/services/common/copier.js~Copier.html#static-method-copy",
    "src/services/common/copier.js~Copier.copy",
    "method"
  ],
  [
    "src/services/common/copier.js~copier.copyfile",
    "class/src/services/common/copier.js~Copier.html#static-method-copyFile",
    "src/services/common/copier.js~Copier.copyFile",
    "method"
  ],
  [
    "src/services/common/copier.js~copier.copymodule",
    "class/src/services/common/copier.js~Copier.html#static-method-copyModule",
    "src/services/common/copier.js~Copier.copyModule",
    "method"
  ],
  [
    "src/services/common/copier.js~copier.findmissingitems",
    "class/src/services/common/copier.js~Copier.html#static-method-findMissingItems",
    "src/services/common/copier.js~Copier.findMissingItems",
    "method"
  ],
  [
    "src/services/common/copier.js~copier.pathexists",
    "class/src/services/common/copier.js~Copier.html#static-method-pathExists",
    "src/services/common/copier.js~Copier.pathExists",
    "method"
  ],
  [
    "src/services/common/events.js",
    "file/src/services/common/events.js.html",
    "src/services/common/events.js",
    "file"
  ],
  [
    "src/services/common/index.js",
    "file/src/services/common/index.js.html",
    "src/services/common/index.js",
    "file"
  ],
  [
    "src/services/common/plugins.js",
    "file/src/services/common/plugins.js.html",
    "src/services/common/plugins.js",
    "file"
  ],
  [
    "src/services/common/plugins.js~plugins#app",
    "class/src/services/common/plugins.js~Plugins.html#instance-member-app",
    "src/services/common/plugins.js~Plugins#app",
    "member"
  ],
  [
    "src/services/common/plugins.js~plugins#applogger",
    "class/src/services/common/plugins.js~Plugins.html#instance-member-appLogger",
    "src/services/common/plugins.js~Plugins#appLogger",
    "member"
  ],
  [
    "src/services/common/plugins.js~plugins#constructor",
    "class/src/services/common/plugins.js~Plugins.html#instance-constructor-constructor",
    "src/services/common/plugins.js~Plugins#constructor",
    "method"
  ],
  [
    "src/services/common/plugins.js~plugins#load",
    "class/src/services/common/plugins.js~Plugins.html#instance-method-load",
    "src/services/common/plugins.js~Plugins#load",
    "method"
  ],
  [
    "src/services/common/plugins.js~plugins#packageinfo",
    "class/src/services/common/plugins.js~Plugins.html#instance-member-packageInfo",
    "src/services/common/plugins.js~Plugins#packageInfo",
    "member"
  ],
  [
    "src/services/common/plugins.js~plugins#pathutils",
    "class/src/services/common/plugins.js~Plugins.html#instance-member-pathUtils",
    "src/services/common/plugins.js~Plugins#pathUtils",
    "member"
  ],
  [
    "src/services/common/plugins.js~plugins#prefix",
    "class/src/services/common/plugins.js~Plugins.html#instance-member-prefix",
    "src/services/common/plugins.js~Plugins#prefix",
    "member"
  ],
  [
    "src/services/common/versionutils.js",
    "file/src/services/common/versionUtils.js.html",
    "src/services/common/versionUtils.js",
    "file"
  ],
  [
    "src/services/common/versionutils.js~versionutils#applogger",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-member-appLogger",
    "src/services/common/versionUtils.js~VersionUtils#appLogger",
    "member"
  ],
  [
    "src/services/common/versionutils.js~versionutils#constructor",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-constructor-constructor",
    "src/services/common/versionUtils.js~VersionUtils#constructor",
    "method"
  ],
  [
    "src/services/common/versionutils.js~versionutils#createrevisionfile",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-method-createRevisionFile",
    "src/services/common/versionUtils.js~VersionUtils#createRevisionFile",
    "method"
  ],
  [
    "src/services/common/versionutils.js~versionutils#environmentutils",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-member-environmentUtils",
    "src/services/common/versionUtils.js~VersionUtils#environmentUtils",
    "member"
  ],
  [
    "src/services/common/versionutils.js~versionutils#fallbackversion",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-member-fallbackVersion",
    "src/services/common/versionUtils.js~VersionUtils#fallbackVersion",
    "member"
  ],
  [
    "src/services/common/versionutils.js~versionutils#getenvironmentversion",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-method-getEnvironmentVersion",
    "src/services/common/versionUtils.js~VersionUtils#getEnvironmentVersion",
    "method"
  ],
  [
    "src/services/common/versionutils.js~versionutils#getversion",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-method-getVersion",
    "src/services/common/versionUtils.js~VersionUtils#getVersion",
    "method"
  ],
  [
    "src/services/common/versionutils.js~versionutils#getversionfromfile",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-method-getVersionFromFile",
    "src/services/common/versionUtils.js~VersionUtils#getVersionFromFile",
    "method"
  ],
  [
    "src/services/common/versionutils.js~versionutils#pathutils",
    "class/src/services/common/versionUtils.js~VersionUtils.html#instance-member-pathUtils",
    "src/services/common/versionUtils.js~VersionUtils#pathUtils",
    "member"
  ],
  [
    "src/services/configurations/babelconfiguration.js",
    "file/src/services/configurations/babelConfiguration.js.html",
    "src/services/configurations/babelConfiguration.js",
    "file"
  ],
  [
    "src/services/configurations/babelconfiguration.js~babelconfiguration#constructor",
    "class/src/services/configurations/babelConfiguration.js~BabelConfiguration.html#instance-constructor-constructor",
    "src/services/configurations/babelConfiguration.js~BabelConfiguration#constructor",
    "method"
  ],
  [
    "src/services/configurations/babelconfiguration.js~babelconfiguration#events",
    "class/src/services/configurations/babelConfiguration.js~BabelConfiguration.html#instance-member-events",
    "src/services/configurations/babelConfiguration.js~BabelConfiguration#events",
    "member"
  ],
  [
    "src/services/configurations/babelconfiguration.js~babelconfiguration#getconfigfortarget",
    "class/src/services/configurations/babelConfiguration.js~BabelConfiguration.html#instance-method-getConfigForTarget",
    "src/services/configurations/babelConfiguration.js~BabelConfiguration#getConfigForTarget",
    "method"
  ],
  [
    "src/services/configurations/babelconfiguration.js~babelconfiguration#plugins",
    "class/src/services/configurations/babelConfiguration.js~BabelConfiguration.html#instance-member-plugins",
    "src/services/configurations/babelConfiguration.js~BabelConfiguration#plugins",
    "member"
  ],
  [
    "src/services/configurations/index.js",
    "file/src/services/configurations/index.js.html",
    "src/services/configurations/index.js",
    "file"
  ],
  [
    "src/services/configurations/projectconfiguration.js",
    "file/src/services/configurations/projectConfiguration.js.html",
    "src/services/configurations/projectConfiguration.js",
    "file"
  ],
  [
    "src/services/configurations/projectconfiguration.js~projectconfiguration#constructor",
    "class/src/services/configurations/projectConfiguration.js~ProjectConfiguration.html#instance-constructor-constructor",
    "src/services/configurations/projectConfiguration.js~ProjectConfiguration#constructor",
    "method"
  ],
  [
    "src/services/configurations/projectconfiguration.js~projectconfiguration#createconfig",
    "class/src/services/configurations/projectConfiguration.js~ProjectConfiguration.html#instance-method-createConfig",
    "src/services/configurations/projectConfiguration.js~ProjectConfiguration#createConfig",
    "method"
  ],
  [
    "src/services/configurations/targetconfiguration.js",
    "file/src/services/configurations/targetConfiguration.js.html",
    "src/services/configurations/targetConfiguration.js",
    "file"
  ],
  [
    "src/services/configurations/targetconfiguration.js~targetconfiguration#constructor",
    "class/src/services/configurations/targetConfiguration.js~TargetConfiguration.html#instance-constructor-constructor",
    "src/services/configurations/targetConfiguration.js~TargetConfiguration#constructor",
    "method"
  ],
  [
    "src/services/configurations/targetconfiguration.js~targetconfiguration#createconfig",
    "class/src/services/configurations/targetConfiguration.js~TargetConfiguration.html#instance-method-createConfig",
    "src/services/configurations/targetConfiguration.js~TargetConfiguration#createConfig",
    "method"
  ],
  [
    "src/typedef.js",
    "file/src/typedef.js.html",
    "src/typedef.js",
    "file"
  ],
  [
    "src/typedef.js~appconfiguration",
    "https://homer0.github.io/wootils/class/wootils/node/appConfiguration.js~AppConfiguration.html",
    "src/typedef.js~AppConfiguration",
    "external"
  ],
  [
    "src/typedef.js~browsertarget",
    "typedef/index.html#static-typedef-BrowserTarget",
    "src/typedef.js~BrowserTarget",
    "typedef"
  ],
  [
    "src/typedef.js~buildengine",
    "typedef/index.html#static-typedef-BuildEngine",
    "src/typedef.js~BuildEngine",
    "typedef"
  ],
  [
    "src/typedef.js~buildenginegetcommand",
    "typedef/index.html#static-typedef-BuildEngineGetCommand",
    "src/typedef.js~BuildEngineGetCommand",
    "typedef"
  ],
  [
    "src/typedef.js~command",
    "https://tj.github.io/commander.js/#Command",
    "src/typedef.js~Command",
    "external"
  ],
  [
    "src/typedef.js~environmentutils",
    "https://homer0.github.io/wootils/class/wootils/node/environmentUtils.js~EnvironmentUtils.html",
    "src/typedef.js~EnvironmentUtils",
    "external"
  ],
  [
    "src/typedef.js~errorhandler",
    "https://homer0.github.io/wootils/class/wootils/node/errorHandler.js~ErrorHandler.html",
    "src/typedef.js~ErrorHandler",
    "external"
  ],
  [
    "src/typedef.js~eventshub",
    "https://homer0.github.io/wootils/class/wootils/shared/eventsHub.js~EventsHub.html",
    "src/typedef.js~EventsHub",
    "external"
  ],
  [
    "src/typedef.js~jimple",
    "https://yarnpkg.com/en/package/jimple",
    "src/typedef.js~Jimple",
    "external"
  ],
  [
    "src/typedef.js~logger",
    "https://homer0.github.io/wootils/class/wootils/node/logger.js~Logger.html",
    "src/typedef.js~Logger",
    "external"
  ],
  [
    "src/typedef.js~nodetarget",
    "typedef/index.html#static-typedef-NodeTarget",
    "src/typedef.js~NodeTarget",
    "typedef"
  ],
  [
    "src/typedef.js~nodemon",
    "https://github.com/remy/nodemon/blob/master/doc/requireable.md",
    "src/typedef.js~Nodemon",
    "external"
  ],
  [
    "src/typedef.js~pathutils",
    "https://homer0.github.io/wootils/class/wootils/node/pathUtils.js~PathUtils.html",
    "src/typedef.js~PathUtils",
    "external"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplate",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplate",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplate",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplatebabelsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplateBabelSettings",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplateBabelSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplateconfigurationsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplateConfigurationSettings",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplateConfigurationSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplatedevserversettings",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplateDevServerSettings",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplateDevServerSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplatedevelopmentoutputpaths",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplateDevelopmentOutputPaths",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplateDevelopmentOutputPaths",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplatehtmlsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplateHTMLSettings",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplateHTMLSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplateoutput",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplateOutput",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplateOutput",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplateproductionoutputpaths",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplateProductionOutputPaths",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplateProductionOutputPaths",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationbrowsertargettemplatesourcemapsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationBrowserTargetTemplateSourceMapSettings",
    "src/typedef.js~ProjectConfigurationBrowserTargetTemplateSourceMapSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationcopyfeaturesettings",
    "typedef/index.html#static-typedef-ProjectConfigurationCopyFeatureSettings",
    "src/typedef.js~ProjectConfigurationCopyFeatureSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationfeaturetriggersettings",
    "typedef/index.html#static-typedef-ProjectConfigurationFeatureTriggerSettings",
    "src/typedef.js~ProjectConfigurationFeatureTriggerSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationnodetargettemplate",
    "typedef/index.html#static-typedef-ProjectConfigurationNodeTargetTemplate",
    "src/typedef.js~ProjectConfigurationNodeTargetTemplate",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationnodetargettemplatebabelsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationNodeTargetTemplateBabelSettings",
    "src/typedef.js~ProjectConfigurationNodeTargetTemplateBabelSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationnodetargettemplateoutput",
    "typedef/index.html#static-typedef-ProjectConfigurationNodeTargetTemplateOutput",
    "src/typedef.js~ProjectConfigurationNodeTargetTemplateOutput",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationothersettings",
    "typedef/index.html#static-typedef-ProjectConfigurationOtherSettings",
    "src/typedef.js~ProjectConfigurationOtherSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationpathsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationPathSettings",
    "src/typedef.js~ProjectConfigurationPathSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationSettings",
    "src/typedef.js~ProjectConfigurationSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationtargettemplateentry",
    "typedef/index.html#static-typedef-ProjectConfigurationTargetTemplateEntry",
    "src/typedef.js~ProjectConfigurationTargetTemplateEntry",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationtargettemplatelibraryoptions",
    "typedef/index.html#static-typedef-ProjectConfigurationTargetTemplateLibraryOptions",
    "src/typedef.js~ProjectConfigurationTargetTemplateLibraryOptions",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationtargettemplates",
    "typedef/index.html#static-typedef-ProjectConfigurationTargetTemplates",
    "src/typedef.js~ProjectConfigurationTargetTemplates",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationversionrevisionsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationVersionRevisionSettings",
    "src/typedef.js~ProjectConfigurationVersionRevisionSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationversionsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationVersionSettings",
    "src/typedef.js~ProjectConfigurationVersionSettings",
    "typedef"
  ],
  [
    "src/typedef.js~projectconfigurationwatchsettings",
    "typedef/index.html#static-typedef-ProjectConfigurationWatchSettings",
    "src/typedef.js~ProjectConfigurationWatchSettings",
    "typedef"
  ],
  [
    "src/typedef.js~provider",
    "typedef/index.html#static-typedef-Provider",
    "src/typedef.js~Provider",
    "typedef"
  ],
  [
    "src/typedef.js~providerregistermethod",
    "typedef/index.html#static-typedef-ProviderRegisterMethod",
    "src/typedef.js~ProviderRegisterMethod",
    "typedef"
  ],
  [
    "src/typedef.js~rootrequire",
    "https://homer0.github.io/wootils/function/index.html#static-function-rootRequire",
    "src/typedef.js~RootRequire",
    "external"
  ],
  [
    "src/typedef.js~target",
    "typedef/index.html#static-typedef-Target",
    "src/typedef.js~Target",
    "typedef"
  ],
  [
    "src/typedef.js~targetconfigurationcreator",
    "typedef/index.html#static-typedef-TargetConfigurationCreator",
    "src/typedef.js~TargetConfigurationCreator",
    "typedef"
  ],
  [
    "src/typedef.js~targetfolders",
    "typedef/index.html#static-typedef-TargetFolders",
    "src/typedef.js~TargetFolders",
    "typedef"
  ],
  [
    "src/typedef.js~targetpaths",
    "typedef/index.html#static-typedef-TargetPaths",
    "src/typedef.js~TargetPaths",
    "typedef"
  ],
  [
    "src/typedef.js~targettypecheck",
    "typedef/index.html#static-typedef-TargetTypeCheck",
    "src/typedef.js~TargetTypeCheck",
    "typedef"
  ],
  [
    "src/typedef.js~watchpack",
    "https://yarnpkg.com/en/package/watchpack",
    "src/typedef.js~Watchpack",
    "external"
  ]
]